dist: xenial
os:
    - linux
language: c
compiler: gcc
branches:
    only:
        - master
script:
    - make test

deploy:
    provider: releases
    file: res.out
    skip_cleanup: true
    on:
        tags: true
