dist: xenial
os:
    - linux
language: c
compiler: gcc
branches:
    only:
        - master
script:
    - make test

deploy:
    provider: releases
    file: ./les3/bin/res.out
    skip_cleanup: true
    on:
        tags: true
