dist: xenial
os:
    - linux

language: c
compiler: gcc

script:
    - make test

deploy:
    provider: releases
    api_key:
        secure: $GIT_TOKEN
    file: test.out
    skip_cleanup: true
    on:
        tags: true
